import { Router } from "express";
import userAuthRoutes         from "./user.auth.routes.js";
import vendorAuthRoutes       from "./vendor.auth.routes.js";
import vendorProfileRoutes    from "./vendor.profile.routes.js";
import vendorUploadRoutes     from "./vendor.upload.routes.js";
import vendorInquiryRoutes    from "./vendor.inquiry.routes.js";
import vendorHallsRoutes      from "./vendor.halls.routes.js";
import vendorReviewRoutes     from "./vendor.review.routes.js";
import vendorBookingRoutes    from "./vendor.booking.routes.js";
import vendorQuotationRoutes  from "./vendor.quotation.routes.js";
import vendorStaffRoutes      from "./vendor.staff.routes.js";
import vendorPackageRoutes    from "./vendor.package.routes.js";
import vendorReportsRoutes         from "./vendor.reports.routes.js";
import vendorNotificationsRoutes   from "./vendor.notifications.routes.js";
import adminVendorsRoutes     from "./admin.vendors.routes.js";
import adminAuthRoutes        from "./admin.auth.routes.js";
import adminBookingsRoutes    from "./admin.bookings.routes.js";
import adminReviewsRoutes     from "./admin.reviews.routes.js";
import adminDashboardRoutes      from "./admin.dashboard.routes.js";
import adminNotificationsRoutes  from "./admin.notifications.routes.js";
import adminFeaturedRoutes       from "./admin.featured.routes.js";
import adminApplicationsRoutes  from "./admin.applications.routes.js";
import adminReportsRoutes        from "./admin.reports.routes.js";
import adminUsersRoutes          from "./admin.users.routes.js";
import adminPromoBannersRoutes  from "./admin.promo-banners.routes.js";
import publicContactRoutes      from "./public.contact.routes.js";

const router = Router();

router.use("/admin/auth",        adminAuthRoutes);
router.use("/admin/vendors",     adminVendorsRoutes);
router.use("/admin/bookings",    adminBookingsRoutes);
router.use("/admin/reviews",     adminReviewsRoutes);
router.use("/admin/dashboard",       adminDashboardRoutes);
router.use("/admin/notifications",   adminNotificationsRoutes);
router.use("/admin/featured",        adminFeaturedRoutes);
router.use("/admin/applications",    adminApplicationsRoutes);
router.use("/admin/reports",         adminReportsRoutes);
router.use("/admin/users",           adminUsersRoutes);
router.use("/admin/promo-banners",   adminPromoBannersRoutes);
router.use("/contact",               publicContactRoutes);
router.use("/user/auth",         userAuthRoutes);
router.use("/vendor/auth",       vendorAuthRoutes);
router.use("/vendor/profile",    vendorProfileRoutes);
router.use("/vendor/upload",     vendorUploadRoutes);
router.use("/vendor/inquiry",    vendorInquiryRoutes);
router.use("/vendor/halls",      vendorHallsRoutes);
router.use("/vendor/review",     vendorReviewRoutes);
router.use("/vendor/bookings",   vendorBookingRoutes);
router.use("/vendor/quotations", vendorQuotationRoutes);
router.use("/vendor/staff",      vendorStaffRoutes);
router.use("/vendor/packages",   vendorPackageRoutes);
router.use("/vendor/reports",        vendorReportsRoutes);
router.use("/vendor/notifications",  vendorNotificationsRoutes);

export default router;
